version: '3.1'

services:
  db: 
    image: mongo
    restart: always
    container_name: database
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: property
    ports: 
      - 27017:27017
  server: 
    build: .
    container_name: server
    ports: 
      - 8080:8080