version: '3.1'

services:
  db: 
    image: mongo
    container_name: database
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: property
    ports: 
      - 27018:27017
  # server: 
  #   build: .
  #   container_name: server
  #   links:
  #    - "db:mongo"
  #   ports: 
  #     - 8080:8080